### ISSUE TITLE
Send file in service

### ISSUE THREAD

**Issue by SimaAmini** [kzrfaisal/angular-file-uploader#13]
I need to send file through service and send csrf with file .Is there any example to help me?

**Comment by kzrfaisal** [comment]
Hi @SimaAmini ,
Right Now you can utilize the code instead of npm package, in later versions this functionality will be available, but for time being you can send you csrf with the file by giving it inside 'caption' property.
Link ( Line num: 336 ):-   https://github.com/kzrfaisal/angular-file-uploader/blob/master/projects/angular-file-uploader/src/lib/angular-file-uploader.component.ts

**Comment by SimaAmini** [comment]
Thanks for your quick reply. I'm new to angular and I find it so difficult to understand your code. Would you please provide an example for me?

**Comment by SimaAmini** [comment]
I could send Csrf not cookie and sessionId . thank you anyway.
