### ISSUE TITLE
No event raised on file drop

### ISSUE THREAD

**Issue by djaud** [kzrfaisal/angular-file-uploader#98]
When a file is dropped into the file uploader no event is raised, the only two EventEmitters are 'ApiResponse' and 'everythingDone' and neither fires.

I think this would be a basic requirement for a lot of users, could this be implemented?

**Comment by kzrfaisal** [comment]
@djaud 
`everythingDone` event emitter is not available, that's why it is also not mentioned on README.
And I just checked `APIResponse` event emitter for 'dragNDrop' theme and it is found to be working.
![image](https://user-images.githubusercontent.com/13894812/133227737-37907214-7dd8-412d-9f2b-1c10eb42f65d.png)

**Comment by kzrfaisal** [comment]
@djaud 
If you can provide some more details regarding how you have implemented it and your current environment, may I can help.

**Comment by djaud** [comment]
Sorry, it seems I didn't make myself clear. Once the file is uploaded 'APIResponse' fires, but I was talking about an event which fires when the file is dropped (before upload)

![image](https://user-images.githubusercontent.com/8792786/133237533-7d669e63-d43a-4ff0-b29c-43535f06a97a.png)

**Comment by kzrfaisal** [comment]
@djaud 
okay, for that any event emitter is not available. I'll try to add it in the next release.

**Comment by kzrfaisal** [comment]
file drop or selected event has been added as `fileSelected` in version `7.1.0`
